[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rla-health"  # distribution name (can contain '-'); import package is 'rla'
version = "0.0.1"
description = "Robust & Lightweight Health TSAD"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["rla*"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["rla"]
combine_as_imports = true
force_sort_within_sections = true
